name: 🎨 Windows
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: "windows-latest"
    name: Setup
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons pywin32
          python --version
          scons --version

  build-64-release:
    runs-on: "windows-latest"
    name: Build 64-Bit Release (scons platform=windows target=release bits=64)
    steps:
      - name: Compilation
        run: |
          scons platform=windows target=release bits=64

      - uses: actions/upload-artifact@v2
        with:
          name: gdsdk_64_release
          path: demo/bin/windows-64/gdsdk.dll

  build-64-debug:
    runs-on: "windows-latest"
    name: Build 64-Bit Release (scons platform=windows target=release bits=64)
    steps:
      - name: Compilation
        run: |
          scons platform=windows target=release bits=64

      - uses: actions/upload-artifact@v2
        with:
          name: gdsdk_64_debug
          path: demo/bin/windows-64/gdsdk.dll

  build-32-release:
    runs-on: "windows-latest"
    name: Build 32-Bit Release (scons platform=windows target=release bits=32)
    steps:
      - name: Compilation
        run: |
          scons platform=windows target=release bits=32

      - uses: actions/upload-artifact@v2
        with:
          name: gdsdk_32_release
          path: demo/bin/windows-32/gdsdk.dll

  build-32-debug:
    runs-on: "windows-latest"
    name: Build 32-Bit Release (scons platform=windows target=release bits=32)
    steps:
      - name: Compilation
        run: |
          scons platform=windows target=release bits=32

      - uses: actions/upload-artifact@v2
        with:
          name: gdsdk_32_debug
          path: demo/bin/windows-32/gdsdk.dll
